name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew --version > brew-version.0
      - uses: actions/upload-artifact@v3
        with:
          name: brew-version
          path: brew-version.0
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: rcs
      - run: rcs --version
      - run: test "${{ steps.action.outputs.cache-hit }}" != true

  cached:
    needs: initial
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: brew-version
      - run: ls -l; test -f brew-version.0
      - run: |
          : check cache status
          if brew --version | diff -u brew-version.0 -
          then
              echo brew version is same
          else
              error="Test does not make sence, since brew --version does not match."
              echo "::stop-commands::$error"
              echo "$error" 1>&2
          fi
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: rcs
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
      - run: rcs --version
