name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: macos-latest
    outputs:
      brew-version: ${{ steps.brew-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - id: brew-version
        run: |
          version="$(brew --version | head -1)"
          echo "::set-output name=version::$version"
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: rcs
      - run: rcs --version
      - run: test "${{ steps.action.outputs.cache-hit }}" != true

  cached:
    needs: initial
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          : check cache status
          initial="${{ needs.initial.outputs.brew-version }}"
          current="$(brew --version | sed -n 1p)"
          if [ "$initial" != "$current" ]
          then
              error="Test does not make sence ($initial != $current)"
              echo "$error" 1>&2
              echo "::warning ::$error"
              echo "::stop-commands::$error"
          fi
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: rcs
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
      - run: rcs --version
